### ISSUE TITLE
Chronological order

### ISSUE THREAD

**Issue by Akshatha-Mohan** [ketann26/Automatic-Circuit-Recognition#1]
Hello,
I'm trying to learn and your project seems very interesting. But, since there are so many python files.
Would like to know the order of execution.

Thank you

**Comment by ketann26** [comment]
Hi, thanks for showing interest in this project. 
For trying out the project, you may run the schematic_generator.py file. All other files are just supporting files and as skim through
the code, they're gonna come in play. Also we had made an execucutable (.exe) file for the same if you'd like you can also check that out at https://drive.google.com/drive/folders/1Fq1qxhh7EvmzFClNkrodZy9LykA8sVSA?usp=sharing
